---
title: "Assignment 1: Introduction"
author: David Robinson
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assigment section on Sakai.


## 1) Finish setting up R Studio

### Install TinyTex
Now, run this code cell the same way. This will install "tinytex" -- a helper app that allows you to knit your markdown documents into professional quality PDFs.
```{r install tiny tex, eval=FALSE, include=FALSE}
#install tinytext
tinytex::install_tinytex()
```

### Set your default knit directory
This setting will help deal with relative paths later on...
 - From the Tool menu, select `Global Options`
 - Select the RMarkdown section
 - In the "Evaluate chunks in directory", set the option to "Project" (If you don't see this option, try restarting RStudio.)


## 2) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: 
Formal training includes some undergraduate coursework in statistics (we used R) and computer science (we used Python). I also have five years of work experience in consulting -- we mostly used Excel, but also some Tableau and SQL (a long time ago) for data analytics. Informal training includes work experience in consulting per above (thinking of "on the job" training here). I have no formal or informal training in Git.

2. Are there any components of the course about which you feel confident?

> Answer: 
On the "4-Data Wrangling" component, I have a decent bit of experience with these concepts in Excel (but not in R).

3. Are there any components of the course about which you feel apprehensive?

> Answer: 
Git is brand new for me, as is Time Series Analysis, Spatial Analysis, and Data Scraping.

## 3) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: 
https://github.com/david-h-robinson/EDE_Fall2023

## 4) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Sakai. 
